api:
  version: "1.0"
application:
  name: "poc-exception-handler"  
CONTINUE:
  HTTP:
    CONNECTIVITY: "409"
PROPAGATE:
  APP:
    NO_SERVICE: "409"
  HTTP:
    NOT_FOUND: "404"
  APIKIT:
    NOT_FOUND: "404"
    METHOD_NOT_ALLOWED: "405"

"404": "Resource Not Found"
"405": "Method Not Allowed"
"409": "Conflict"
